on: [push, merge]
  branches:
    - master
name: 🚀 Deploy website
jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Get latest code
      uses: actions/checkout@master

    - name: Use lastest Node.js
      uses: actions/setup-node@master

    - name: Build Project
      run: |
        npm install
        npm run build

    - name: Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.0.0
      with:
        server: ftp.gutsfun.com
        username: ${{ secrets.GUTSFUN_FTP_USER }}
        password: ${{ secrets.GUTSFUN_FTP_PASSWORD }}
        local-dir: ./dist
        exclude:
          - img/**
          - static/**