name: 🚀 Deploy website

on:
  workflow_dispatch:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]

jobs:
  web-deploy:

    runs-on: windows-latest

    steps:
    - name: Get latest code
      uses: actions/checkout@master

    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '12.x'

    - name: Build Project
      run: |
        npm install
        npm run build

    - name: Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.0.0
      with:
        server: ftp.gutsfun.com
        username: ${{ secrets.GUTSFUN_FTP_USER }}
        password: ${{ secrets.GUTSFUN_FTP_PASSWORD }}
        local-dir: ./dist/
        exclude: img/**
          - static/**

